name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RUN_LEAK_TESTS: 'false'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install virtualenv
          python -m virtualenv .venv
          source .venv/bin/activate
          pip install -r requirements-dev.txt
      - name: Run import checks
        run: |
          source .venv/bin/activate
          python tools/check_imports.py
      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest -q

  leak-tests:
    # Run always but skip early if RUN_LEAK_TESTS != 'true' (avoids static analyzer issue)
    if: always()
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Guard - skip unless RUN_LEAK_TESTS=true
        run: |
          if [ "${RUN_LEAK_TESTS:-}" != "true" ]; then
            echo "RUN_LEAK_TESTS not enabled; skipping leak-tests job.";
            exit 0
          fi
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install tor utilities (only available on linux runners)
        run: |
          sudo apt update
          sudo apt install -y tor torsocks privoxy curl
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install virtualenv
          python -m virtualenv .venv
          source .venv/bin/activate
          pip install -r requirements-dev.txt || true
      - name: Run leak-tests (requires tor running)
        run: |
          # start tor in the background for the duration of the job
          sudo systemctl start tor || sudo tor &
          sleep 3
          python tools/leak_test.py
